version: '3.8'
services:
    gnbsim:
        container_name: gnbsim
        image: gnbsim:latest
        privileged: true
        environment:
            - MCC=208
            - MNC=95
            - GNBID=1
            - TAC=0x00a000
            - SST=222
            - SD=00007b
            - PagingDRX=v32
            - RANUENGAPID=0
            - IMEISV=35609204079514
            - MSIN=0000000031
            - RoutingIndicator=1234
            - ProtectionScheme=null
            - KEY=0C0A34601D4F07677303652C0462535B
            - OPc=63bfa50ee6523365ff14c1f45f88737d
            - DNN=default
            - URL=http://www.asnt.org:8080/
            - NRCellID=1
            - USE_FQDN=no
            - NGAPPeerAddr=192.168.70.132
            - GTPuLocalAddr=192.168.70.136
            - GTPuIFname=eth0
        networks:
            public_net:
                ipv4_address: 192.168.70.136
        healthcheck:
            test: /bin/bash -c "ifconfig gtp-gnb"
            interval: 10s
            timeout: 5s
            retries: 5
    gnbsim2:
        container_name: gnbsim2
        image: gnbsim:latest
        privileged: true
        environment:
            - MCC=208
            - MNC=95
            - GNBID=2
            - TAC=0x00a000
            - SST=222
            - SD=00007b
            - PagingDRX=v32
            - RANUENGAPID=0
            - IMEISV=35609204079514
            - MSIN=0000000032
            - RoutingIndicator=1234
            - ProtectionScheme=null
            - KEY=0C0A34601D4F07677303652C0462535B
            - OPc=63bfa50ee6523365ff14c1f45f88737d
            - DNN=default
            - URL=http://www.asnt.org:8080/
            - NRCellID=1
            - USE_FQDN=no
            - NGAPPeerAddr=192.168.70.132
            - GTPuLocalAddr=192.168.70.137
            - GTPuIFname=eth0
        networks:
            public_net:
                ipv4_address: 192.168.70.137
        healthcheck:
            test: /bin/bash -c "ifconfig gtp-gnb"
            interval: 10s
            timeout: 5s
            retries: 5
    gnbsim3:
        container_name: gnbsim3
        image: gnbsim:latest
        privileged: true
        environment:
            - MCC=208
            - MNC=95
            - GNBID=3
            - TAC=0x00a000
            - SST=222
            - SD=00007b
            - PagingDRX=v32
            - RANUENGAPID=0
            - IMEISV=35609204079514
            - MSIN=0000000033
            - RoutingIndicator=1234
            - ProtectionScheme=null
            - KEY=0C0A34601D4F07677303652C0462535B
            - OPc=63bfa50ee6523365ff14c1f45f88737d
            - DNN=default
            - URL=http://www.asnt.org:8080/
            - NRCellID=1
            - USE_FQDN=no
            - NGAPPeerAddr=192.168.70.132
            - GTPuLocalAddr=192.168.70.138
            - GTPuIFname=eth0
        networks:
            public_net:
                ipv4_address: 192.168.70.138
        healthcheck:
            test: /bin/bash -c "ifconfig gtp-gnb"
            interval: 10s
            timeout: 5s
            retries: 5
    gnbsim4:
        container_name: gnbsim4
        image: gnbsim:latest
        privileged: true
        environment:
            - MCC=208
            - MNC=95
            - GNBID=4
            - TAC=0x00a000
            - SST=222
            - SD=00007b
            - PagingDRX=v32
            - RANUENGAPID=0
            - IMEISV=35609204079514
            - MSIN=0000000034
            - RoutingIndicator=1234
            - ProtectionScheme=null
            - KEY=0C0A34601D4F07677303652C0462535B
            - OPc=63bfa50ee6523365ff14c1f45f88737d
            - DNN=default
            - URL=http://www.asnt.org:8080/
            - NRCellID=1
            - USE_FQDN=no
            - NGAPPeerAddr=192.168.70.132
            - GTPuLocalAddr=192.168.70.139
            - GTPuIFname=eth0
        networks:
            public_net:
                ipv4_address: 192.168.70.139
        healthcheck:
            test: /bin/bash -c "ifconfig gtp-gnb"
            interval: 10s
            timeout: 5s
            retries: 5
    gnbsim5:
        container_name: gnbsim5
        image: gnbsim:latest
        privileged: true
        environment:
            - MCC=208
            - MNC=95
            - GNBID=5
            - TAC=0x00a000
            - SST=222
            - SD=00007b
            - PagingDRX=v32
            - RANUENGAPID=0
            - IMEISV=35609204079514
            - MSIN=0000000035
            - RoutingIndicator=1234
            - ProtectionScheme=null
            - KEY=0C0A34601D4F07677303652C0462535B
            - OPc=63bfa50ee6523365ff14c1f45f88737d
            - DNN=default
            - URL=http://www.asnt.org:8080/
            - NRCellID=1
            - USE_FQDN=no
            - NGAPPeerAddr=192.168.70.132
            - GTPuLocalAddr=192.168.70.140
            - GTPuIFname=eth0
        networks:
            public_net:
                ipv4_address: 192.168.70.140
        healthcheck:
            test: /bin/bash -c "ifconfig gtp-gnb"
            interval: 10s
            timeout: 5s
            retries: 5
    gnbsim-fqdn:
        container_name: gnbsim-fqdn
        image: gnbsim:latest
        privileged: true
        environment:
            - MCC=208
            - MNC=95
            - GNBID=5
            - TAC=0x00a000
            - SST=222
            - SD=00007b
            - PagingDRX=v32
            - RANUENGAPID=0
            - IMEISV=35609204079514
            - MSIN=0000000035
            - RoutingIndicator=1234
            - ProtectionScheme=null
            - KEY=0C0A34601D4F07677303652C0462535B
            - OPc=63bfa50ee6523365ff14c1f45f88737d
            - DNN=default
            - URL=http://www.asnt.org:8080/
            - NRCellID=1
            - USE_FQDN=yes
            - AMF_FQDN=amf.oai-5gc.eur
            - GTPuIFname=eth0
        networks:
            public_net:
        healthcheck:
            test: /bin/bash -c "ifconfig gtp-gnb"
            interval: 10s
            timeout: 5s
            retries: 5
    gnbsim-vpp:
        container_name: gnbsim-vpp
        image: gnbsim:latest
        privileged: true
        environment:
            - MCC=208
            - MNC=95
            - GNBID=5
            - TAC=0x00a000
            - SST=222
            - SD=00007b
            - PagingDRX=v32
            - RANUENGAPID=0
            - IMEISV=35609204079514
            - MSIN=0000000035
            - RoutingIndicator=1234
            - ProtectionScheme=null
            - KEY=0C0A34601D4F07677303652C0462535B
            - OPc=63bfa50ee6523365ff14c1f45f88737d
            - DNN=default
            - URL=http://www.asnt.org:8080/
            - NRCellID=1
            - USE_FQDN=no
#           - USE_FQDN=yes
#           - AMF_FQDN=amf.oai-5gc.eur
            - NGAPPeerAddr=192.168.71.132
            - GTPuLocalAddr=192.168.72.141
            - GTPuIFname=eth1
        networks:
            public_net_core:
                ipv4_address: 192.168.71.141
            public_net_access:
                ipv4_address: 192.168.72.141
        healthcheck:
            test: /bin/bash -c "ifconfig gtp-gnb"
            interval: 10s
            timeout: 5s
            retries: 5
networks:
    public_net:
        external:
            name: demo-oai-public-net
    public_net_core:
        name: oai-public-core
        ipam:
            config:
                - subnet: 192.168.71.0/24
    public_net_access:
        name: oai-public-access
        ipam:
            config:
                - subnet: 192.168.72.0/24
# Incase the user wants docker-compose to create a bridge rather than creating the bridge manually then uncomment the below lines
#     public_net:
#         driver: bridge
#         name: demo-oai-public-net
#         ipam:
#             config:
#                 - subnet: 192.168.70.128/26
#         driver_opts:
#             com.docker.network.bridge.name: "demo-oai"
